//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogId { get; set; }
        public int NetworkObjectId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string NetworkObjectName { get; set; }
        public string UserName { get; set; }
    }
}
