//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.AssetCategoryLinks = new HashSet<AssetCategoryLink>();
            this.OverriddenCategories = new HashSet<Category>();
            this.CategoryMenuLinks = new HashSet<CategoryMenuLink>();
            this.CategoryMenuLinks1 = new HashSet<CategoryMenuLink>();
            this.CategoryObjects = new HashSet<CategoryObject>();
            this.SubCategoryLinks = new HashSet<SubCategoryLink>();
            this.SubCategoryLinks1 = new HashSet<SubCategoryLink>();
            this.SubCategoryLinks2 = new HashSet<SubCategoryLink>();
            this.MenuCategoryScheduleLinks = new HashSet<MenuCategoryScheduleLink>();
        }
    
        public int CategoryId { get; set; }
        public bool ShowPrice { get; set; }
        public string InternalName { get; set; }
        public string DisplayName { get; set; }
        public bool IsFeatured { get; set; }
        public CategoryTypes CategoryTypeId { get; set; }
        public int MenuId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int NetworkObjectId { get; set; }
        public Nullable<int> OverrideCategoryId { get; set; }
        public long IrisId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string DeepLinkId { get; set; }
    
        public virtual ICollection<AssetCategoryLink> AssetCategoryLinks { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual ICollection<Category> OverriddenCategories { get; set; }
        public virtual Category OverriddenParentCategory { get; set; }
        public virtual ICollection<CategoryMenuLink> CategoryMenuLinks { get; set; }
        public virtual ICollection<CategoryMenuLink> CategoryMenuLinks1 { get; set; }
        public virtual ICollection<CategoryObject> CategoryObjects { get; set; }
        public virtual ICollection<SubCategoryLink> SubCategoryLinks { get; set; }
        public virtual ICollection<SubCategoryLink> SubCategoryLinks1 { get; set; }
        public virtual ICollection<SubCategoryLink> SubCategoryLinks2 { get; set; }
        public virtual ICollection<MenuCategoryScheduleLink> MenuCategoryScheduleLinks { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
