//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    
    public enum CollectionTypeNames : int
    {
        Modification = 1,
        Substitution = 2,
        UpSell = 3,
        CrossSell = 4,
        Combo = 5,
        EndOfOrder = 6
    }
}
