//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuisine
    {
        public Cuisine()
        {
            this.CuisineNetworkObjectLinks = new HashSet<CuisineNetworkObjectLink>();
        }
    
        public int CuisineId { get; set; }
        public string CuisineName { get; set; }
    
        public virtual ICollection<CuisineNetworkObjectLink> CuisineNetworkObjectLinks { get; set; }
    }
}
