//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWGroup
    {
        public DWGroup()
        {
            this.DWGroup1 = new HashSet<DWGroup>();
            this.DWGroupItemLinks = new HashSet<DWGroupItemLink>();
        }
    
        public int DWGroupKey { get; set; }
        public Nullable<int> Parent { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int grp_id { get; set; }
    
        public virtual ICollection<DWGroup> DWGroup1 { get; set; }
        public virtual DWGroup DWGroup2 { get; set; }
        public virtual ICollection<DWGroupItemLink> DWGroupItemLinks { get; set; }
    }
}
