//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWGroupItemLink
    {
        public int DWGroupItemLink1 { get; set; }
        public int DWGroupKey { get; set; }
        public int ItemId { get; set; }
    
        public virtual DWGroup DWGroup { get; set; }
        public virtual Item Item { get; set; }
    }
}
