//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWItemCookTime
    {
        public DWItemCookTime()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int DWItemCookTimeKey { get; set; }
        public Nullable<int> CookTimeMinutes { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
