//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWItemLookup
    {
        public DWItemLookup()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int DWItemLookupKey { get; set; }
        public int TypeId { get; set; }
        public string Abbreviation { get; set; }
        public string LookupValue { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Sequence { get; set; }
        public int lookup_id { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
