//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWItemSubType
    {
        public DWItemSubType()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int DWItemSubTypeKey { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int DWItemTypeKey { get; set; }
        public int item_type_id { get; set; }
        public int item_sub_type_id { get; set; }
    
        public virtual DWItemType DWItemType { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
