//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportMapping
    {
        public int ImportMappingId { get; set; }
        public System.Guid DataId { get; set; }
        public int ImportDataRowId { get; set; }
        public long IrisId { get; set; }
        public int DataRowId { get; set; }
        public string DataRowType { get; set; }
        public int MenuNetworkObjectLinkId { get; set; }
    
        public virtual MenuNetworkObjectLink MenuNetworkObjectLink { get; set; }
    }
}
