//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPOSDataLink
    {
        public int ItemPOSDataLinkId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> POSDataId { get; set; }
        public bool IsDefault { get; set; }
        public int NetworkObjectId { get; set; }
        public Nullable<int> ParentMasterItemId { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual POSData POSData { get; set; }
    }
}
