//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCollectionLink
    {
        public int CollectionLinkId { get; set; }
        public int SortOrder { get; set; }
        public int ItemId { get; set; }
        public int CollectionId { get; set; }
        public int NetworkObjectId { get; set; }
        public Nullable<int> ParentCollectionId { get; set; }
        public OverrideStatus OverrideStatus { get; set; }
    
        public virtual ItemCollection ItemCollection { get; set; }
        public virtual ItemCollection ItemCollection1 { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual Item Item { get; set; }
    }
}
