//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCollectionType
    {
        public ItemCollectionType()
        {
            this.ItemCollections = new HashSet<ItemCollection>();
        }
    
        public int CollectionTypeId { get; set; }
        public CollectionTypeNames CollectionTypeName { get; set; }
    
        public virtual ICollection<ItemCollection> ItemCollections { get; set; }
    }
}
