//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCollection
    {
        public ItemCollection()
        {
            this.ItemCollectionObjects = new HashSet<ItemCollectionObject>();
            this.ItemCollectionLinks = new HashSet<ItemCollectionLink>();
            this.ItemCollectionLinks1 = new HashSet<ItemCollectionLink>();
            this.OverriddenCollections = new HashSet<ItemCollection>();
        }
    
        public int CollectionId { get; set; }
        public string InternalName { get; set; }
        public string DisplayName { get; set; }
        public bool ShowPrice { get; set; }
        public int MinQuantity { get; set; }
        public int MaxQuantity { get; set; }
        public int MenuId { get; set; }
        public CollectionTypeNames CollectionTypeId { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsPropagate { get; set; }
        public int NetworkObjectId { get; set; }
        public bool IsVisibleToGuest { get; set; }
        public bool ReplacesItem { get; set; }
        public long IrisId { get; set; }
        public Nullable<int> OverrideCollectionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<ItemCollectionObject> ItemCollectionObjects { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual ICollection<ItemCollectionLink> ItemCollectionLinks { get; set; }
        public virtual ICollection<ItemCollectionLink> ItemCollectionLinks1 { get; set; }
        public virtual ICollection<ItemCollection> OverriddenCollections { get; set; }
        public virtual ItemCollection OverriddenParentCollection { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
