//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.AssetItemLinks = new HashSet<AssetItemLink>();
            this.CategoryObjects = new HashSet<CategoryObject>();
            this.CategoryObjects1 = new HashSet<CategoryObject>();
            this.DWGroupItemLinks = new HashSet<DWGroupItemLink>();
            this.ItemCollectionObjects = new HashSet<ItemCollectionObject>();
            this.ChildItems = new HashSet<Item>();
            this.OverriddenItems = new HashSet<Item>();
            this.ItemCollectionLinks = new HashSet<ItemCollectionLink>();
            this.ItemCollectionObjects1 = new HashSet<ItemCollectionObject>();
            this.ItemDescriptions = new HashSet<ItemDescription>();
            this.ItemPOSDataLinks = new HashSet<ItemPOSDataLink>();
            this.ItemPOSDataLinks1 = new HashSet<ItemPOSDataLink>();
            this.MenuItemScheduleLinks = new HashSet<MenuItemScheduleLink>();
            this.PrependItemLinks = new HashSet<PrependItemLink>();
            this.PrependItemLinks1 = new HashSet<PrependItemLink>();
            this.PrependItemLinks2 = new HashSet<PrependItemLink>();
            this.TempSchedules = new HashSet<TempSchedule>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string DisplayName { get; set; }
        public string DisplayDescription { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsModifier { get; set; }
        public bool IsIncluded { get; set; }
        public bool IsEnabled { get; set; }
        public decimal DiscountedPrice { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public Nullable<int> NutritionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsAvailable { get; set; }
        public bool QuickOrder { get; set; }
        public bool ShowPrice { get; set; }
        public bool IsPriceOverriden { get; set; }
        public decimal OverridenPrice { get; set; }
        public Nullable<int> OverrideItemId { get; set; }
        public bool IsSendHierarchy { get; set; }
        public bool IsTopLevel { get; set; }
        public bool IsCombo { get; set; }
        public bool IsSubstitute { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ButtonText { get; set; }
        public bool PrintOnOrder { get; set; }
        public bool PrintOnReceipt { get; set; }
        public bool PrintOnSameLine { get; set; }
        public bool PrintRecipe { get; set; }
        public bool ForceRecipe { get; set; }
        public bool IsBeverage { get; set; }
        public bool IsEntreeApp { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public int NetworkObjectId { get; set; }
        public bool IsCore { get; set; }
        public string RequestedBy { get; set; }
        public string DeepLinkId { get; set; }
        public bool IsAlcohol { get; set; }
        public Nullable<int> ModifierFlagId { get; set; }
        public long IrisId { get; set; }
        public Nullable<int> DWItemId { get; set; }
        public Nullable<int> DWItemCategorizationKey { get; set; }
        public Nullable<int> DWItemSubTypeKey { get; set; }
        public Nullable<int> CookTime { get; set; }
        public Nullable<int> PrepOrderTime { get; set; }
        public Nullable<int> SelectedDescriptionId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public int Feeds { get; set; }
    
        public virtual ICollection<AssetItemLink> AssetItemLinks { get; set; }
        public virtual ICollection<CategoryObject> CategoryObjects { get; set; }
        public virtual ICollection<CategoryObject> CategoryObjects1 { get; set; }
        public virtual ICollection<DWGroupItemLink> DWGroupItemLinks { get; set; }
        public virtual DWItemCategorization DWItemCategorization { get; set; }
        public virtual DWItemCookTime DWItemCookTime { get; set; }
        public virtual DWItemLookup DWItemLookup { get; set; }
        public virtual DWItemSubType DWItemSubType { get; set; }
        public virtual ICollection<ItemCollectionObject> ItemCollectionObjects { get; set; }
        public virtual ICollection<Item> ChildItems { get; set; }
        public virtual Item MasterItem { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual ModifierFlag ModifierFlag { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual Nutrition Nutrition { get; set; }
        public virtual ICollection<Item> OverriddenItems { get; set; }
        public virtual Item OverriddenParentItem { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual ItemDescription ItemDescription { get; set; }
        public virtual ICollection<ItemCollectionLink> ItemCollectionLinks { get; set; }
        public virtual ICollection<ItemCollectionObject> ItemCollectionObjects1 { get; set; }
        public virtual ICollection<ItemDescription> ItemDescriptions { get; set; }
        public virtual ICollection<ItemPOSDataLink> ItemPOSDataLinks { get; set; }
        public virtual ICollection<ItemPOSDataLink> ItemPOSDataLinks1 { get; set; }
        public virtual ICollection<MenuItemScheduleLink> MenuItemScheduleLinks { get; set; }
        public virtual ICollection<PrependItemLink> PrependItemLinks { get; set; }
        public virtual ICollection<PrependItemLink> PrependItemLinks1 { get; set; }
        public virtual ICollection<PrependItemLink> PrependItemLinks2 { get; set; }
        public virtual ICollection<TempSchedule> TempSchedules { get; set; }
    }
}
