//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapStatusType
    {
        public MapStatusType()
        {
            this.Recipes = new HashSet<Recipe>();
            this.POSDatas = new HashSet<POSData>();
        }
    
        public int MapTypeId { get; set; }
        public int MapTypeName { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
        public virtual ICollection<POSData> POSDatas { get; set; }
    }
}
