//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCategoryCycleInSchedule
    {
        public int CategoryScheduleCycleId { get; set; }
        public int CategoryScheduleLinkId { get; set; }
        public int SchCycleId { get; set; }
        public bool IsShow { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual SchCycle SchCycle { get; set; }
        public virtual MenuCategoryScheduleLink MenuCategoryScheduleLink { get; set; }
    }
}
