//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuNetworkObjectLinks = new HashSet<MenuNetworkObjectLink>();
            this.CategoryMenuLinks = new HashSet<CategoryMenuLink>();
            this.Categories = new HashSet<Category>();
            this.ItemCollections = new HashSet<ItemCollection>();
            this.MenuTagLinks = new HashSet<MenuTagLink>();
            this.Items = new HashSet<Item>();
        }
    
        public int MenuId { get; set; }
        public string InternalName { get; set; }
        public string Description { get; set; }
        public int NetworkObjectId { get; set; }
        public long IrisId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<MenuNetworkObjectLink> MenuNetworkObjectLinks { get; set; }
        public virtual ICollection<CategoryMenuLink> CategoryMenuLinks { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<ItemCollection> ItemCollections { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual ICollection<MenuTagLink> MenuTagLinks { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
