//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuNetworkObjectLink
    {
        public MenuNetworkObjectLink()
        {
            this.SpecialNoticeMenuLinks = new HashSet<SpecialNoticeMenuLink>();
            this.PrependItemLinks = new HashSet<PrependItemLink>();
            this.ImportMappings = new HashSet<ImportMapping>();
        }
    
        public int MenuNetworkObjectLinkId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public int NetworkObjectId { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public bool IsPOSMapped { get; set; }
        public bool IsMenuOverriden { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual ICollection<SpecialNoticeMenuLink> SpecialNoticeMenuLinks { get; set; }
        public virtual ICollection<PrependItemLink> PrependItemLinks { get; set; }
        public virtual ICollection<ImportMapping> ImportMappings { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
