//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTagLink
    {
        public int MenuTagLinkId { get; set; }
        public int MenuId { get; set; }
        public int TagId { get; set; }
        public int NetworkObjectId { get; set; }
        public OverrideStatus OverrideStatus { get; set; }
        public Nullable<int> ParentTagId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual Tag OverriddenParentTag { get; set; }
        public virtual Tag SelectedTag { get; set; }
    }
}
