//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSyncTarget
    {
        public MenuSyncTarget()
        {
            this.TargetTagLinks = new HashSet<TargetTagLink>();
        }
    
        public int MenuSyncTargetId { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Token { get; set; }
        public string LastSyncStatus { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public int NetworkObjectId { get; set; }
        public string ApplicationIdentifier { get; set; }
    
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual ICollection<TargetTagLink> TargetTagLinks { get; set; }
    }
}
