//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModifierFlag
    {
        public ModifierFlag()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ModifierFlagId { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public int NetworkObjectId { get; set; }
    
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
