//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkObjectType
    {
        public NetworkObjectType()
        {
            this.NetworkObjects = new HashSet<NetworkObject>();
        }
    
        public int NetworkObjectTypeId { get; set; }
        public NetworkObjectTypes NetworkObjectType1 { get; set; }
    
        public virtual ICollection<NetworkObject> NetworkObjects { get; set; }
    }
}
