//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    
    public enum NetworkObjectTypes : int
    {
        Root = 1,
        Brand = 2,
        Franchise = 3,
        Market = 4,
        Site = 5
    }
}
