//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrition
    {
        public Nutrition()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int NutritionId { get; set; }
        public int NetCalories { get; set; }
        public string FatCalories { get; set; }
        public int ServingSize { get; set; }
        public string DailyPercent { get; set; }
        public string TotalCarb { get; set; }
        public string Protein { get; set; }
        public string VitaminA { get; set; }
        public string VitaminB { get; set; }
        public string VitaminC { get; set; }
        public string Iron { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
