//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhoenixODSContext : DbContext
    {
        public PhoenixODSContext()
            : base("name=PhoenixODSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ODSIngredient> ODSIngredients { get; set; }
        public DbSet<ODSRecipe> ODSRecipes { get; set; }
        public DbSet<ODSUnitOfMeasure> ODSUnitOfMeasures { get; set; }
        public DbSet<ODSPOSData> ODSPOSDatas { get; set; }
    }
}
