//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSPOSData
    {
        public int POSDataId { get; set; }
        public int PLU { get; set; }
        public string ItemName { get; set; }
        public bool IsModifier { get; set; }
        public bool IsSold { get; set; }
        public int ScreenGroup { get; set; }
        public string ScreenGroupName { get; set; }
        public int ScreenPos { get; set; }
        public decimal BasePrice { get; set; }
        public int Chain1 { get; set; }
        public int Chain2 { get; set; }
        public int Chain3 { get; set; }
        public int Chain4 { get; set; }
        public int Chain5 { get; set; }
        public int DeptNo { get; set; }
        public string DeptName { get; set; }
        public int CookTime { get; set; }
        public string TaxTypeIds { get; set; }
        public decimal ComboPrice { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public long IrisId { get; set; }
    }
}
