//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSRecipe
    {
        public ODSRecipe()
        {
            this.ODSIngredients = new HashSet<ODSIngredient>();
            this.ODSRecipe1 = new HashSet<ODSRecipe>();
        }
    
        public int RecipeId { get; set; }
        public Nullable<int> ParentRecipeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> StarChefGUID { get; set; }
        public int Servings { get; set; }
        public decimal Cost { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<ODSIngredient> ODSIngredients { get; set; }
        public virtual ICollection<ODSRecipe> ODSRecipe1 { get; set; }
        public virtual ODSRecipe ODSRecipe2 { get; set; }
        public virtual ODSUnitOfMeasure ODSUnitOfMeasure { get; set; }
    }
}
