//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODSUnitOfMeasure
    {
        public ODSUnitOfMeasure()
        {
            this.ODSIngredients = new HashSet<ODSIngredient>();
            this.ODSRecipes = new HashSet<ODSRecipe>();
        }
    
        public int UnitOfMeasureId { get; set; }
        public string UnitOfMeasure { get; set; }
    
        public virtual ICollection<ODSIngredient> ODSIngredients { get; set; }
        public virtual ICollection<ODSRecipe> ODSRecipes { get; set; }
    }
}
