//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSData
    {
        public POSData()
        {
            this.ItemPOSDataLinks = new HashSet<ItemPOSDataLink>();
        }
    
        public int POSDataId { get; set; }
        public Nullable<int> PLU { get; set; }
        public string POSItemName { get; set; }
        public bool IsModifier { get; set; }
        public bool IsSold { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public int NetworkObjectId { get; set; }
        public string AlternatePLU { get; set; }
        public string ExternalId { get; set; }
        public string MenuItemName { get; set; }
        public bool IsAlcohol { get; set; }
        public string ButtonText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ICollection<ItemPOSDataLink> ItemPOSDataLinks { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
