//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    
    public partial class POSMappedItemsResult
    {
        public string ParentName { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string DisplayName { get; set; }
        public string DisplayDescription { get; set; }
        public Nullable<int> MappedPLU { get; set; }
        public Nullable<int> MappedPOSDataId { get; set; }
        public string MappedPOSItemName { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> LinkedAt { get; set; }
        public int IsOverride { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public bool IsAvailable { get; set; }
    }
}
