//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.RecipeChildren = new HashSet<Recipe>();
            this.Items = new HashSet<Item>();
        }
    
        public int RecipeId { get; set; }
        public Nullable<int> ParentRecipeId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> StarChefGUID { get; set; }
        public int Servings { get; set; }
        public decimal Cost { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<int> UnitOfMeasureId { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<MapStatusTypes> MapTypeId { get; set; }
    
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<Recipe> RecipeChildren { get; set; }
        public virtual Recipe RecipeParent { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
