//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    
    public enum Roles : int
    {
        Guest = 1,
        Viewer = 2,
        Editor = 3,
        Administrator = 4,
        SuperAdministrator = 5
    }
}
