//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchCycle
    {
        public SchCycle()
        {
            this.MenuCategoryCycleInSchedules = new HashSet<MenuCategoryCycleInSchedule>();
            this.MenuItemCycleInSchedules = new HashSet<MenuItemCycleInSchedule>();
            this.SchCycle1 = new HashSet<SchCycle>();
            this.SchDetails = new HashSet<SchDetail>();
        }
    
        public int SchCycleId { get; set; }
        public string CycleName { get; set; }
        public int SortOrder { get; set; }
        public int NetworkObjectId { get; set; }
        public Nullable<int> ParentSchCycleId { get; set; }
        public OverrideStatus OverrideStatus { get; set; }
    
        public virtual ICollection<MenuCategoryCycleInSchedule> MenuCategoryCycleInSchedules { get; set; }
        public virtual ICollection<MenuItemCycleInSchedule> MenuItemCycleInSchedules { get; set; }
        public virtual ICollection<SchCycle> SchCycle1 { get; set; }
        public virtual SchCycle SchCycle2 { get; set; }
        public virtual ICollection<SchDetail> SchDetails { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
