//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.SchNetworkObjectLinks = new HashSet<SchNetworkObjectLink>();
            this.SchNetworkObjectLinks1 = new HashSet<SchNetworkObjectLink>();
            this.SchDetails = new HashSet<SchDetail>();
        }
    
        public int ScheduleId { get; set; }
        public string SchName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public long IrisId { get; set; }
    
        public virtual ICollection<SchNetworkObjectLink> SchNetworkObjectLinks { get; set; }
        public virtual ICollection<SchNetworkObjectLink> SchNetworkObjectLinks1 { get; set; }
        public virtual ICollection<SchDetail> SchDetails { get; set; }
    }
}
