//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchNetworkObjectLink
    {
        public int SchNetworkObjectLinkId { get; set; }
        public int ScheduleId { get; set; }
        public int NetworkObjectId { get; set; }
        public Nullable<int> ParentScheduleId { get; set; }
        public OverrideStatus OverrideStatus { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int Priority { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Schedule Schedule1 { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
