//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerivceNetworkObjectLink
    {
        public int SerivceNetworkObjectLinkId { get; set; }
        public int ServiceTypeId { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<int> MinOrder { get; set; }
        public Nullable<int> EstimatedTime { get; set; }
        public Nullable<int> TaxTypeId { get; set; }
        public Nullable<int> AreaCovered { get; set; }
        public int NetworkObjectId { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
