//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialNoticeMenuLink
    {
        public int SpecialNoticeMenuLinkId { get; set; }
        public int NoticeId { get; set; }
        public int MenuNetworkObjectLinkId { get; set; }
        public bool IsLinked { get; set; }
    
        public virtual MenuNetworkObjectLink MenuNetworkObjectLink { get; set; }
        public virtual SpecialNotice SpecialNotice { get; set; }
    }
}
