//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagAssetLinks = new HashSet<TagAssetLink>();
            this.MenuTagLinks = new HashSet<MenuTagLink>();
            this.MenuTagLinks1 = new HashSet<MenuTagLink>();
            this.TargetTagLinks = new HashSet<TargetTagLink>();
        }
    
        public int Id { get; set; }
        public string TagName { get; set; }
        public int NetworkObjectId { get; set; }
        public string TagKey { get; set; }
    
        public virtual ICollection<TagAssetLink> TagAssetLinks { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
        public virtual ICollection<MenuTagLink> MenuTagLinks { get; set; }
        public virtual ICollection<MenuTagLink> MenuTagLinks1 { get; set; }
        public virtual ICollection<TargetTagLink> TargetTagLinks { get; set; }
    }
}
