//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int UserPermissionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> NetworkObjectId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual NetworkObject NetworkObject { get; set; }
    }
}
