//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.webpages_ExtraUserInformation = new HashSet<webpages_ExtraUserInformation>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.UserPermissions = new HashSet<UserPermission>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<webpages_ExtraUserInformation> webpages_ExtraUserInformation { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
    }
}
