//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwItemwithPOS
    {
        public Nullable<long> Row { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string DisplayName { get; set; }
        public string DeepLinkId { get; set; }
        public Nullable<int> POSDataId { get; set; }
        public Nullable<int> BasePLU { get; set; }
        public string AlternatePLU { get; set; }
        public string POSItemName { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public Nullable<int> OverrideItemId { get; set; }
        public int NetworkObjectId { get; set; }
        public long IrisId { get; set; }
    }
}
