//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwNetworkObjectTree
    {
        public long Row { get; set; }
        public int Root { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> Franchise { get; set; }
        public Nullable<int> Market { get; set; }
        public Nullable<int> Site { get; set; }
    }
}
