//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPOSwithItem
    {
        public long Row { get; set; }
        public Nullable<int> POSDataId { get; set; }
        public Nullable<int> PLU { get; set; }
        public string POSItemName { get; set; }
        public Nullable<bool> IsModifier { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public int NetworkObjectId { get; set; }
        public string AlternatePLU { get; set; }
        public string ExternalId { get; set; }
        public string MenuItemName { get; set; }
        public Nullable<bool> IsAlcohol { get; set; }
        public string ButtonText { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> BasePLU { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> ParentItemId { get; set; }
        public Nullable<int> OverrideItemId { get; set; }
        public Nullable<long> IrisId { get; set; }
    }
}
